name: overseer
description: A human-in-the-loop testing framework for manually verifying backend artifacts like videos, audio, and AI output.
version: 1.0.0
repository: https://github.com/Thomasssb1/overseer

environment:
  sdk: "^3.3.0"

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0
  ansi_styles: ^0.3.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
