name: Dart CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.9.0"

      - name: Install dependencies
        run: dart pub get

      - name: Format project source
        run: dart format .

      - name: Auto-commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format Dart code"
          file_pattern: "**/*.dart"

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
